obj-$(CONFIG_HGICS)    += hgics.o

hgics-objs += core.o
hgics-objs += rx.o
hgics-objs += ap.o
hgics-objs += util.o
hgics-objs += event.o
hgics-objs += procfs.o
hgics-objs += hw.o
hgics-objs += ../utils/utils.o
hgics-objs += ../utils/fwdl.o
hgics-objs += ../utils/fwctrl.o
hgics-objs += ../utils/ota.o
hgics-objs += ../utils/fwinfo.o
hgics-objs += ../utils/iwpriv.o
hgics-objs += ../utils/bluetooth.o

hgics-$(CONFIG_HGIC_SDIO) += ../utils/if_sdio.o
hgics-$(CONFIG_HGIC_USB)  += ../utils/if_usb.o

hgics-$(CONFIG_HGIC_2G) += 11bgn.o
hgics-$(CONFIG_HGIC_AH) += 11ah.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/ap.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/chan.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/core.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/mlme.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/nl80211.o
#hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/radiotap.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/reg.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/scan.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/sme.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/util.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/ap.o
hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/sysfs.o
#hgics-$(CONFIG_HGIC_AH) += umac/cfg80211/ethtool.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/agg-rx.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/agg-tx.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/cfg.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/chan.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/event.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/ht.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/vht.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/iface.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/key.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/main.o
#hgics-$(CONFIG_HGIC_AH) += umac/mac80211/wpa.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/michael.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/mlme.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/offchannel.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/rate.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/rx.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/s1g.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/scan.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/spectmgmt.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/sta_info.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/status.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/tx.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/util.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/vht.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/wme.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/wbnat.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/wbnat_arp.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/wbnat_ip.o
hgics-$(CONFIG_HGIC_AH) += umac/mac80211/pm.o


hgics-$(CONFIG_HGIC_STABR) += stabr.o stabr_arp.o stabr_ip.o

